написал разметку к главной странице
htmlacademy-htmlcss/1837591-sedona-32 pull request #2
Opened 2021-09-28 06:11 UTC by bitnik93

2021-09-28 09:11 UTC, summertime-fms requested changes

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                <ul class="navigation-list" class="navigation-user">
Классы через пробел можно в одном атрибуте class перечислять.

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                        <button type="button" class="signin-button" id="signinButton">
Давай придерживаться кодгайда. Если везде первым атрибутом ставишь класс то тут тоже надо. А затем уже type

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                            Вход
А почему вход? Есть какая то инфа что делает эта кнопка?

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +            <img class="index-background" src="" alt ="Фон Гостиниц Седона">
Декоративное

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                </h2>
форматирование. Текст либо между двумя тегами на отдельной строке либо и теги и текст на одной строке

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                        <img class="photo-1" src="" alt="фото городка" >
Форматирование. Пробел перед закрывающей скобкой лучше убрать. Везде.

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                        <li class="advantages-item">
Форматиование. Вложенность не отображена. Нужна табуляция

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                            <img class="icon-1" src="" alt="иконка жилья" >
Иконки мы договорились делать через css. В разметке давай уберем

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                        <h3 class="advantage-title">НЕБОЛЬШАЯ ПЛОЗАДЬ</h3>
опечатка в слове площадь

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +            <section>
Форма входит в секцию подпишитесь на рассылку. В преддущую

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                    <label class="visually-hidden" for="newsletter-email"></label>
Текст надо добавить в этот тег)

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                        <span class="visually-hidden">ПОДПИСАТЬСЯ</span>
А почему visually-hidden? В макете же есть текст в кнопке. И вообще в спан оборачивать нет надобности. Это лишний тег тут, текст отобразится в кнопке и так.

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                        <span class="vissualy-hidden">Твиттер</span>
вложеннооость

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                        <a class="button" href="https://twitter.com/htmlacademy_ru">
Кнопками у нас будут коричневые прямоугольники. Это может быть просто social-item

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +            <section class="footer-contacts">
Слабо тянет на секцию. Секции - крупные смысловые блоки. В main ты хорошо выделил их. А тут всего два теги внутри. МОжно не оборачивать чтобы не плодить вложенность. В то же время ошибкой это считаться не будет, смотри сам, как тебе удобно. Выше в соц сетях тоже можно убрать section и h2 тогда уже.

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                <h2>+7 (812) 812-12-12</h2>
Давай лучше разметим ссылкой с протоколом tel  https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/tel

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +            <div>
Убирай section оставляй див с классом copyright. Что то из этого явно лишняя обертка.

2021-09-28 09:11 UTC, summertime-fms commented on index.html
> +                <img class="logo-html" src="https://htmlacademy.ru/" alt="Логотип html">
Вложенность

2021-09-29 07:02 UTC, bitnik93 commented on index.html
> +                    </li>
добавил ли

2021-09-30 07:43 UTC, merged

2021-09-30 08:04 UTC, summertime-fms commented on catalog.html
> +                        <img class="product-card-four-stars" src="" alt="4 звезды">
Убирай это из разметки, мы сделаем более изящно и доступно

2021-09-30 08:04 UTC, summertime-fms commented on catalog.html
> +                        <img class="product-card-image" src="" alt="">
Не забываем про alt.  Маленькая рекомендация - лучше ставить точку в конце каждого альта.  Тогда скринридер (программа которая читает твой сайт для незрячих) интонационно разделит текст.

2021-09-30 08:04 UTC, summertime-fms commented on catalog.html
> +                    <button class="button-favorite" type="submit">В ИЗБРАННОЕ</button>
почему сабмит-то? Это button

2021-09-30 08:04 UTC, summertime-fms commented on catalog.html
> +                <label class="visually-hidden" for="newsletter-email">ПОДПИСАТЬСЯ</label>
капс убираем

2021-09-30 08:04 UTC, summertime-fms commented on catalog.html
> +                <label class="visually-hidden" for="newsletter-email">ПОДПИСАТЬСЯ</label>
и сверху и снизу и вообще везде